name: Build and Push Multi-Platform Docker Image

on:
  push:
    tags:
      - 'v*.*.*'  # Se ejecuta solo cuando se crea un tag semántico (v1.0.0, v2.1.3, etc.)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract tag name
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Multi-Platform Image
        run: |
          docker buildx create --use
          docker buildx build \
            --platform linux/amd64,linux/arm64,linux/arm/v7 \
            --tag ${{ secrets.DOCKER_USERNAME }}/mikrotik-backup-over-ssh:${{ env.VERSION }} \
            --tag ${{ secrets.DOCKER_USERNAME }}/mikrotik-backup-over-ssh:latest \
            --push .
